Escape mosquitto_passwd command line.
The options need to be escaped, for instance a password
with `)` results in.

```
Error: /usr/bin/mosquitto_passwd -b /etc/mosquitto/infra_service.pw infra XXXXXX) returned 2 instead of one of [0]
Error: /Stage[main]/Mosquitto::Server/Exec[passwd_file]/returns: change from notrun to 0 failed: /usr/bin/mosquitto_passwd -b /etc/mosquitto/infra_service.pw infra ylVR2wq6) returned 2 instead of one of [0]
```